name: Backup

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "11 7 * * *" # daily at 7:11 AM UTC

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"
    - name: Create run.sh if it doesn't exist
      run: |
        [ -f "run.sh" ] && exit 0
        echo "#!/bin/bash" > run.sh
        if [[ "$REPO_DESC" == @* ]] || [[ "$REPO_DESC" == did:* ]]; then
          echo "./backup.sh $REPO_DESC" >> run.sh
        else
          echo "# ./backup.sh @bsky.app" >> run.sh
        fi
        chmod +x run.sh
        echo "Created run.sh"
        echo -e "# Scheduled Bluesky backup\n\nFor \`$REPO_DESC\`." > README.md 
      env:
        REPO_DESC: ${{ github.event.repository.description }}
    - name: Run the scraper
      run: |
        ./run.sh
    - name: Setup Restic
      uses: AnimMouse/setup-restic@v1
    - name: Push to Restic repo
      run: restic backup
      env:
        RESTIC_REPOSITORY: ${{ secrets.RESTIC_REPOSITORY }}
        RESTIC_PASSWORD: ${{ secrets.RESTIC_PASSWORD }}
        RESTIC_BACKUP_SOURCES: ./car_files
        RESTIC_BACKUP_ARGS: |
          --tag pds
        RESTIC_FORGET_ARGS: |
          --keep-last 10
          --keep-daily 7
          --keep-weekly 5
          --keep-monthly 12
